var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = y[op[0] & 2 ? "return" : op[0] ? "throw" : "next"]) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [0, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
var directiveScopeReadyLimit = 10;
var directiveScopeReadyTimeout = 200;
$(document).keyup(function (e) {
    if (e.which === 13 && Joove.Common.eventPreventsDefaultFormAction(e) === false && !$(e.target).parent().hasClass("search-element")) {
        window._popUpManager.previouslyFocusedElement = document.activeElement;
        $(":focus").blur();
        Joove.Core.getScope().eventCallbacks.cmdDeliveryNoteSaveClicked(e);
    }
    if (e.which === 27 && Joove.Common.eventPreventsDefaultFormAction(e) === false) {
        window._popUpManager.previouslyFocusedElement = document.activeElement;
        $(":focus").blur();
        Joove.Core.getScope().eventCallbacks.cmdExitClicked(e);
    }
});
window.onbeforeunload = function (e) {
    if (window._context.isDirty) {
        var msg = window._resourcesManager.getGlobalResource("RES_WEBFORM_DirtyMessage");
        e.returnValue = msg; // Gecko, Trident, Chrome 34+
        return msg;
    }
};
var DSS5_SupplyChainFinancialsOptimisation;
(function (DSS5_SupplyChainFinancialsOptimisation) {
    var Controllers;
    (function (Controllers) {
        var _this = this;
        var DeliveryNoteFormConditionalFormattings = [
            new Joove.JbRule({
                name: "HideIfNewConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return window._context.currentAction == "AddDeliveryNote"; }, false)];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "DisableIfNotSupplierConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.IsSupplier; }, false)];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "ShowHideInsertProductsConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, CLMS.Framework.Number.GreaterThan(function () { return window["scope_DeliveryNoteForm"].model.SupplierProducts.length; }, function () { return 0; })];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "HideIfNotNewConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return window._context.currentAction == "NewDeliveryNote"; }, false)];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "HideStandardsConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return window._context.currentUsername; }, "") == "Supplier25" || Joove.Common.nullSafe(function () { return window._context.currentUsername; }, "") == "Supplier15"];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "UploadConfirmedConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.UploadConfirmed; }, false)];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
            new Joove.JbRule({
                name: "DisableConfirmUploadConditional",
                type: Joove.RuleTypes.ConditionalFormatting,
                isDataSetRule: false,
                evaluatedAtServer: false,
                contextControlName: null,
                condition: function (_parents) { return __awaiter(_this, void 0, void 0, function () {
                    return __generator(this, function (_a) {
                        return [2 /*return*/, Joove.Common.nullSafe(function () { return CLMS.Framework.String.IsNullOrEmpty(Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.CSVPath; }, "")); }, false)];
                    });
                }); },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange],
                isRelatedToDataValidation: false
            }),
        ];
        var DeliveryNoteFormDataValidations = [];
        var DeliveryNoteFormCalculatedExpressions = [
            new Joove.JbRule({
                name: "DeliveryNoteTotalLinePrice",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            _parents[0].LineTotalPrice = Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return _parents[0].Quantity; }, 0)) * Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return _parents[0].Price; }, 0));
                            return [2 /*return*/, Joove.Common.nullSafe(function () { return _parents[0].LineTotalPrice; }, 0)];
                        });
                    });
                },
                getContext: function (indexes) {
                    var model = window.scope_DeliveryNoteForm.model;
                    var parents = [];
                    try {
                        parents.push(model.DeliveryNote.DeliveryNoteProducts);
                    }
                    catch (e) {
                        parents.push({});
                    }
                    return parents;
                },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange]
            }),
            new Joove.JbRule({
                name: "DeliveryNoteTotalAmount",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        var total, _iproduct, product;
                        return __generator(this, function (_a) {
                            if ((Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null) == null)) {
                                return [2 /*return*/, 0];
                            }
                            else {
                                total = 0;
                                for (_iproduct = 0; _iproduct < (Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null) == null ? 0 : Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null).length); _iproduct++) {
                                    product = Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null)[_iproduct];
                                    if ((CLMS.Framework.Number.Equal(function () { return product.Quantity; }, function () { return 0; }))) {
                                        continue;
                                    }
                                    total = Joove.Common.safeNumber(total) + Joove.Common.safeNumber((Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return product.Quantity; }, 0)) * Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return product.Price; }, 0))));
                                }
                                return [2 /*return*/, total];
                            }
                            return [2 /*return*/];
                        });
                    });
                },
                evaluationTimes: []
            }),
            new Joove.JbRule({
                name: "DeliveryNoteTotalProducts",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        var totalProducts, _iproduct, product;
                        return __generator(this, function (_a) {
                            if ((Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null) == null)) {
                                return [2 /*return*/, 0];
                            }
                            else {
                                totalProducts = 0;
                                for (_iproduct = 0; _iproduct < (Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null) == null ? 0 : Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null).length); _iproduct++) {
                                    product = Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null)[_iproduct];
                                    if ((CLMS.Framework.Number.Equal(function () { return product.Quantity; }, function () { return 0; }))) {
                                        continue;
                                    }
                                    totalProducts = Joove.Common.safeNumber(totalProducts) + Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return product.Quantity; }, 0));
                                }
                                return [2 /*return*/, totalProducts];
                            }
                            return [2 /*return*/];
                        });
                    });
                },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange]
            }),
            new Joove.JbRule({
                name: "GridOrdersTotalPrice",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        var total, _iorder, order;
                        return __generator(this, function (_a) {
                            if ((Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null) == null)) {
                                return [2 /*return*/, 0];
                            }
                            else {
                                total = 0;
                                for (_iorder = 0; _iorder < (Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null) == null ? 0 : Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null).length); _iorder++) {
                                    order = Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null)[_iorder];
                                    if ((CLMS.Framework.Number.Equal(function () { return order.TotalPrice; }, function () { return 0; }))) {
                                        continue;
                                    }
                                    total = Joove.Common.safeNumber(total) + Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return order.TotalPrice; }, 0));
                                }
                                return [2 /*return*/, total];
                            }
                            return [2 /*return*/];
                        });
                    });
                },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange]
            }),
            new Joove.JbRule({
                name: "GridOrdersTotalQuantity",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        var total, _iorder, order;
                        return __generator(this, function (_a) {
                            if ((Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null) == null)) {
                                return [2 /*return*/, 0];
                            }
                            else {
                                total = 0;
                                for (_iorder = 0; _iorder < (Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null) == null ? 0 : Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null).length); _iorder++) {
                                    order = Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Orders; }, null)[_iorder];
                                    if ((CLMS.Framework.Number.Equal(function () { return order.OrderAmount; }, function () { return 0; }))) {
                                        continue;
                                    }
                                    total = Joove.Common.safeNumber(total) + Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return order.OrderAmount; }, 0));
                                }
                                return [2 /*return*/, total];
                            }
                            return [2 /*return*/];
                        });
                    });
                },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange]
            }),
            new Joove.JbRule({
                name: "TotalPriceIfProductsNull",
                type: Joove.RuleTypes.CalculatedExpression,
                evaluatedAtServer: false,
                isDataSetRule: false,
                condition: function (_control) {
                    return __awaiter(this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            return [2 /*return*/, true];
                        });
                    });
                },
                expression: function (_parents) {
                    return __awaiter(this, void 0, void 0, function () {
                        var total, _iproduct, product;
                        return __generator(this, function (_a) {
                            if ((true)) {
                                if ((CLMS.Framework.Number.GreaterThan(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts.length; }, function () { return 0; }))) {
                                    total = 0;
                                    for (_iproduct = 0; _iproduct < (Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null) == null ? 0 : Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null).length); _iproduct++) {
                                        product = Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.DeliveryNoteProducts; }, null)[_iproduct];
                                        if ((CLMS.Framework.Number.Equal(function () { return product.Quantity; }, function () { return 0; }))) {
                                            continue;
                                        }
                                        total = Joove.Common.safeNumber(total) + Joove.Common.safeNumber((Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return product.Quantity; }, 0)) * Joove.Common.safeNumber(Joove.Common.nullSafe(function () { return product.Price; }, 0))));
                                    }
                                    window["scope_DeliveryNoteForm"].model.DeliveryNote.TotalPrice = total;
                                }
                                return [2 /*return*/, ""];
                            }
                            else {
                                return [2 /*return*/, null];
                            }
                            return [2 /*return*/];
                        });
                    });
                },
                evaluationTimes: [Joove.EvaluationTimes.OnLoad, Joove.EvaluationTimes.OnSubmit, Joove.EvaluationTimes.OnChange]
            }),
        ];
        // Datasets Column Info
        var SelectOrder_ColumnInfo = [
            new Joove.Widgets.DataListColumnInfo({
                dataType: "string",
                dataTypeIsEnum: false,
                name: "OrderNumber",
                caption: window._resourcesManager.getDataListColumnCaption("SelectOrder", "OrderNumber", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: 100,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            })
        ];
        window["SelectOrder_ColumnInfo"] = SelectOrder_ColumnInfo;
        var PickList_ColumnInfo = [
            new Joove.Widgets.DataListColumnInfo({
                dataType: "string",
                dataTypeIsEnum: false,
                name: "Code",
                caption: window._resourcesManager.getDataListColumnCaption("PickList", "Code", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: 100,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            }),
            new Joove.Widgets.DataListColumnInfo({
                dataType: "string",
                dataTypeIsEnum: false,
                name: "Description",
                caption: window._resourcesManager.getDataListColumnCaption("PickList", "Description", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: 100,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            }),
            new Joove.Widgets.DataListColumnInfo({
                dataType: "string",
                dataTypeIsEnum: false,
                name: "UnitValue",
                caption: window._resourcesManager.getDataListColumnCaption("PickList", "UnitValue", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: 100,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            }),
            new Joove.Widgets.DataListColumnInfo({
                dataType: "string",
                dataTypeIsEnum: false,
                name: "MeasurementUnit",
                caption: window._resourcesManager.getDataListColumnCaption("PickList", "MeasurementUnit", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: 100,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            }),
            new Joove.Widgets.DataListColumnInfo({
                dataType: "decimal",
                dataTypeIsEnum: false,
                name: "Price",
                caption: window._resourcesManager.getDataListColumnCaption("PickList", "Price", true),
                groupable: true,
                searchable: true,
                visible: true,
                orderable: true,
                editable: false,
                style: "",
                classes: "",
                itemType: Joove.Widgets.DataListColumnItemType.TEXTBOX,
                importable: false,
                supportsAggregators: true,
                length: null,
                formatting: null,
                width: null,
                css: "",
                isEncrypted: false,
                showFullImage: false
            })
        ];
        window["PickList_ColumnInfo"] = PickList_ColumnInfo;
        // Datasets Projection Shemas
        window["SelectOrder_ProjectionScema"] = { DeliveryNote: { Id: '',
                Transaction: { Id: {}
                }
            }
        };
        window["PickList_ProjectionScema"] = {};
        window["ImageBox_ProjectionScema"] = { DeliveryNoteStandardPhoto: {}
        };
        window["FileAttachmentDNote_ProjectionScema"] = { DeliveryNote: { Id: '',
                DNoteAttachment: {}
            }
        };
        window["FileAttachment_ProjectionScema"] = { CSVPath: {}
        };
        window["FileAttachment1_ProjectionScema"] = { DeliveryNoteStandardPath: {}
        };
        var DeliveryNoteFormController = (function () {
            function DeliveryNoteFormController($scope, $timeout) {
                this.$scope = $scope;
                this.controllerActionFinished = function (resetDirty) {
                    //window.scope_DeliveryNoteForm.model = window.scope_DeliveryNoteForm.dehydrate();
                    //window.scope_MasterPage.model = window.scope_DeliveryNoteForm.model;
                    DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.DeliveryNoteFormViewModel._lightCast(window.scope_DeliveryNoteForm.model);
                    // Joove.Common.applyScope(window.scope_DeliveryNoteForm);
                    if (resetDirty) {
                        window._context.isDirty = false;
                    }
                    window._ruleEngine.update(Joove.EvaluationTimes.OnChange);
                };
                window.scope_DeliveryNoteForm = $scope;
                $scope.$onControlChanged = function (event, newValue, dontMakeDirty) {
                    Joove.Core.onChange(event.target, newValue, dontMakeDirty);
                };
                $scope.dehydrate = function (context) {
                    if (context === void 0) { context = null; }
                    return DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.DeliveryNoteFormViewModel._initializeFrom($scope.model, context);
                };
                $scope._validationsMaster = window.scope_MasterPage._validations;
                $scope._validations = { summary: []
                };
                this.init($scope, $timeout);
                $timeout(function () {
                    window._ruleEngine.update(Joove.EvaluationTimes.OnLoad, null, function () {
                        $("body").fadeIn(200);
                    });
                });
            }
            DeliveryNoteFormController.prototype.init = function ($scope, $timeout) {
                var _this = this;
                $scope.model = DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.DeliveryNoteFormViewModel._initializeFrom(window.viewDTO.Model);
                window.scope_MasterPage.model = $scope.model;
                new Joove.ReferencesReconstructor().reconstructReferences($scope.model);
                $scope.trackObject = function (obj) { return Joove.Common.trackObject(obj); };
                //}
                $.connection['eventsHub'].on('__connectedEvent');
                $.connection['eventsHub'].on('forcePageReload', function () {
                    window.onbeforeunload = null;
                    setTimeout(function () {
                        window.location.reload();
                    }, 3000);
                });
                $.connection.hub.start(function () {
                    Joove.Common.getScope().connectedToSignals();
                    Joove.Common.getMasterScope().connectedToSignals();
                });
                $scope.connectedToSignals = function () {
                };
                // Event Listeners
                $scope.events = {};
                $scope.expressions = {};
                // Dataset Handler
                $scope.datasets = {};
                // Controller actions
                $scope.actions = {
                    AddDeliveryNote: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            Joove.Common.autocompleteFix();
                            Joove.Core.executeRedirectControllerAction("DeliveryNoteForm", "AddDeliveryNote", "GET", [], {}, _modalOptions);
                            return [2 /*return*/];
                        });
                    }); },
                    EditDeliveryNote: function (id, _cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            Joove.Common.autocompleteFix();
                            Joove.Core.executeRedirectControllerAction("DeliveryNoteForm", "EditDeliveryNote", "GET", [id], {}, _modalOptions);
                            return [2 /*return*/];
                        });
                    }); },
                    SaveDeliveryNote: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'SaveDeliveryNote',
                                        queryData: [], postData: { 'model': $scope.model },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); },
                    DeleteDeliveryNote: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            Joove.Common.autocompleteFix();
                            window._context.isDirty = false;
                            Joove.Core.executeControllerActionNew({
                                verb: 'POST', controller: 'DeliveryNoteForm', action: 'DeleteDeliveryNote',
                                queryData: [], postData: { 'model': $scope.model },
                                cb: _cb, modalOptions: _modalOptions, event: _e
                            });
                            return [2 /*return*/];
                        });
                    }); },
                    NewDeliveryNote: function (transactionId, _cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            Joove.Common.autocompleteFix();
                            Joove.Core.executeRedirectControllerAction("DeliveryNoteForm", "NewDeliveryNote", "GET", [transactionId], {}, _modalOptions);
                            return [2 /*return*/];
                        });
                    }); },
                    OnOrderSelected: function (orders, _cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'OnOrderSelected',
                                        queryData: [], postData: { 'model': $scope.model, 'orders': orders },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); },
                    InsertProducts: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'InsertProducts',
                                        queryData: [], postData: { 'model': $scope.model },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); },
                    ImportFromCSV: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'ImportFromCSV',
                                        queryData: [], postData: { 'model': $scope.model },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); },
                    SubmitChanges: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'SubmitChanges',
                                        queryData: [], postData: { 'model': $scope.model },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); },
                    Exit: function (_cb, _modalOptions, _e) { return __awaiter(_this, void 0, void 0, function () {
                        return __generator(this, function (_a) {
                            switch (_a.label) {
                                case 0:
                                    Joove.Common.autocompleteFix();
                                    return [4 /*yield*/, window._ruleEngine.update(Joove.EvaluationTimes.OnSubmit)];
                                case 1:
                                    _a.sent();
                                    window._context.isDirty = false;
                                    Joove.Core.executeControllerActionNew({
                                        verb: 'POST', controller: 'DeliveryNoteForm', action: 'Exit',
                                        queryData: [], postData: { 'model': $scope.model },
                                        cb: _cb, modalOptions: _modalOptions, event: _e
                                    });
                                    return [2 /*return*/];
                            }
                        });
                    }); }
                };
                // Events
                $scope.eventCallbacks = {
                    Button1Clicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockButton1Clicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockButton1Clicked);
                        }
                        _this.timeoutDelayLockButton1Clicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                //This is true only when the menu item is clicked programmatically
                                //and occurs when the middle mouse button click is triggered
                                var openInNewWindow = $(e.target).data("openInNewWindow") === true || undefined;
                                if (openInNewWindow)
                                    $(e.target).data("openInNewWindow", undefined);
                                Joove.Core.executeRedirectControllerAction("TransactionForm", "EditTransaction", "GET", [Joove.Common.nullSafe(function () { return window["scope_DeliveryNoteForm"].model.DeliveryNote.Transaction.Id; }, 0)], null, null, openInNewWindow);
                            }, { groups: [], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                        }, 0);
                    },
                    Button2Clicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockButton2Clicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockButton2Clicked);
                        }
                        _this.timeoutDelayLockButton2Clicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                $scope.actions.SubmitChanges(null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: true });
                        }, 0);
                    },
                    ButtonClicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockButtonClicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockButtonClicked);
                        }
                        _this.timeoutDelayLockButtonClicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                $scope.actions.ImportFromCSV(null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: true });
                        }, 0);
                    },
                    SelectOrderOnChange: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (_this.timeoutDelayLockSelectOrderOnChange != null) {
                            $timeout.cancel(_this.timeoutDelayLockSelectOrderOnChange);
                        }
                        _this.timeoutDelayLockSelectOrderOnChange = $timeout(function () {
                            if (e.target) {
                                Joove.Core.onChange(e.target, null, false);
                            }
                            else {
                                Joove.Core.onChange($("[jb-id='" + e + "']").get(0), null, false);
                            }
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                var p_FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel = Joove.Common.nullSafe(function () { return Joove.DatasourceManager.getSelectedItems($("[jb-id='SelectOrder']"), e); }, null);
                                if (eval("DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel") != null && eval("DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel._initializeFrom") != null) {
                                    var _initial = p_FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel;
                                    p_FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel = [];
                                    for (var _i = 0; _i < _initial.length; _i++) {
                                        var _temp = eval("DSS5_SupplyChainFinancialsOptimisation.ViewModels.DeliveryNoteForm.FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel._initializeFrom(_initial[_i])");
                                        p_FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel.push(_temp);
                                    }
                                }
                                $scope.actions.OnOrderSelected(p_FormControls_DeliveryNoteForm_FormControlsDefinition_SelectOrder_PickListControl_SelectedItems_OrderViewModel, null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: false });
                        }, 0);
                    },
                    Button5Clicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockButton5Clicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockButton5Clicked);
                        }
                        _this.timeoutDelayLockButton5Clicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                $scope.actions.InsertProducts(null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: true });
                        }, 0);
                    },
                    cmdDeliveryNoteSaveClicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockcmdDeliveryNoteSaveClicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockcmdDeliveryNoteSaveClicked);
                        }
                        _this.timeoutDelayLockcmdDeliveryNoteSaveClicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                $scope.actions.SaveDeliveryNote(null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: true });
                        }, 0);
                    },
                    cmdDeleteDeliveryNoteClicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockcmdDeleteDeliveryNoteClicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockcmdDeleteDeliveryNoteClicked);
                        }
                        _this.timeoutDelayLockcmdDeleteDeliveryNoteClicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            window._popUpManager.question(window._resourcesManager.getGlobalResource("RES_WEBFORM_GenericConfirmationQuestion"), window._resourcesManager.getEventConfirmation("cmdDeleteDeliveryNote", false), function (isConfirm) {
                                if (!isConfirm)
                                    return;
                                setTimeout(function () {
                                    Joove.Validation.Manager.validateFormAndExecute(function () {
                                        $scope.actions.DeleteDeliveryNote(null, null, e);
                                    }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: false, withRequiredFieldsCheck: false });
                                }, 1000);
                            });
                        }, 0);
                    },
                    cmdExitClicked: function (e, DataItem, _parents) {
                        window._recorder.addState(e);
                        if (e != null) {
                            e.stopPropagation();
                            e.preventDefault();
                        }
                        if (_this.timeoutDelayLockcmdExitClicked != null) {
                            $timeout.cancel(_this.timeoutDelayLockcmdExitClicked);
                        }
                        _this.timeoutDelayLockcmdExitClicked = $timeout(function () {
                            Joove.Common.setControlKeyPressed(e, 0);
                            Joove.Common.setLastClickedElement(e);
                            Joove.Validation.Manager.validateFormAndExecute(function () {
                                $scope.actions.Exit(null, null, e);
                            }, { groups: [Joove.Validation.Constants.ALL_GROUPS], withDataValidationsCheck: true, withRequiredFieldsCheck: true });
                        }, 0);
                    }
                };
                // Rules
                window._ruleEngine.addDataValidations(DeliveryNoteFormDataValidations);
                window._ruleEngine.addConditionalFormattings(DeliveryNoteFormConditionalFormattings);
                window._ruleEngine.addCalculatedExpressions(DeliveryNoteFormCalculatedExpressions);
                window._commander.executeCommands(window.viewDTO.ClientCommands);
                window.viewDTO.ClientCommands = [];
                Joove.Common.setNumberLocalizationSettings();
                Joove.DeveloperApi.init($scope, window.scope_MasterPage);
                window.$formExtend && window.$formExtend();
                window.$onFormLoaded && window.$onFormLoaded();
            };
            return DeliveryNoteFormController;
        }());
        angular.module("Application").controller("DeliveryNoteFormController", ["$scope", "$timeout", DeliveryNoteFormController]);
    })(Controllers = DSS5_SupplyChainFinancialsOptimisation.Controllers || (DSS5_SupplyChainFinancialsOptimisation.Controllers = {}));
})(DSS5_SupplyChainFinancialsOptimisation || (DSS5_SupplyChainFinancialsOptimisation = {}));
