// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using DSS5_SupplyChainFinancialsOptimisation.Services.IntermediaryUser.DataContracts;

namespace DSS5_SupplyChainFinancialsOptimisation.Services
{
    [XmlSerializerFormat]
    [ServiceContract]
    public interface IIntermediaryUserService
    {
        [OperationContract]
        void Create(DSS5_SupplyChainFinancialsOptimisation.Services.IntermediaryUser.DataContracts.IntermediaryUserDTO _newIntermediaryUser, string _RequestSourceIp, string _UserName);

        [OperationContract]
        DSS5_SupplyChainFinancialsOptimisation.Services.IntermediaryUser.DataContracts.IntermediaryUserDTO Get(string userName, string _RequestSourceIp, string _UserName);

        [OperationContract]
        int? Count(string _RequestSourceIp, string _UserName);

        [OperationContract]
        System.Collections.Generic.List<DSS5_SupplyChainFinancialsOptimisation.Services.IntermediaryUser.DataContracts.IntermediaryUserDTO> GetAll(int? _pageSize, int? _pageIndex, string _RequestSourceIp, string _UserName);

        [OperationContract]
        void Save(DSS5_SupplyChainFinancialsOptimisation.Services.IntermediaryUser.DataContracts.IntermediaryUserDTO intermediaryUser, string _RequestSourceIp, string _UserName);

        [OperationContract]
        void Delete(string userName, string _RequestSourceIp, string _UserName);

        [OperationContract]
        bool IsIntermediary(string _username, string _RequestSourceIp, string _UserName);


    }
}