// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using AppCode;
using DSS5_SupplyChainFinancialsOptimisation.BO;
using DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.DeliveryNoteForm;
using Identity = zAppDev.DotNet.Framework.Identity;
using log4net;
using Newtonsoft.Json;
using NHibernate.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Identity;
using zAppDev.DotNet.Framework.Identity.Model;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Mvc;
using zAppDev.DotNet.Framework.Utilities;

namespace DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.DeliveryNoteForm
{

    [RoutePrefix("DeliveryNoteForm")]
    public class DeliveryNoteFormController : ControllerBase<DeliveryNoteFormViewModel, DeliveryNoteFormViewModelDTO>
    {

        /*<Form:DeliveryNoteForm:0/>*/
        public DeliveryNoteFormController()
        {
            _logger = log4net.LogManager.GetLogger(typeof(DeliveryNoteFormController));
            if (ViewModelDTOBase.DTOHelper == null)
            {
                ViewModelDTOBase.DTOHelper = new DTOHelper();
            }
        }

        protected override void ViewModelLoaded()
        {
            var masterViewModel = new DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPage.MasterPageViewModel
            {
                Title = model.Title, Version = model.Version
            };
            _parentController = new MasterPage.MasterPageController(masterViewModel);
            _parentController.IsDirty = IsDirty;
        }

        public void SetModel(DeliveryNoteFormViewModel m)
        {
            @model = m;
        }


        public override void CommitAllFiles()
        {
            FileHelper.PendingUploadInstance.CommitAllFilesNew("DeliveryNoteForm", @model);
        }

        public override void CommitAllFilesLegacy()
        {
            FileHelper.PendingUploadInstance.CommitAllLegacy("DeliveryNoteForm", @model);
        }

        public override void ClearPendingFiles()
        {
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
        }






        [HttpGet]

        [Route("GetViewDTO")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ContentResult GetViewDTO(int hash)
        {
            return Content(GetViewFromViewDTOsDicSerialized(hash));
        }

        [HttpPost]

        [Route("UpdateInstance")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult UpdateInstance()
        {
            return PrepareUpdateInstanceResult(typeof(DeliveryNoteFormViewModel));
        }

        [HttpPost]

        [Route("_Raise")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult _Raise()
        {
            return _RaiseEvent();
        }

        [HttpGet]
        [Route("DownloadFile")]
        [CustomControllerActionFilter(HasDefaultResultView=true)]
        public FileContentResult DownloadFile(string id)
        {
            return FileHelper.PendingDownloadInstance.DownloadByKey("DeliveryNoteForm", id);
        }

        [HttpGet]
        [Route("DownloadFileByPath")]
        [CustomControllerActionFilter(HasDefaultResultView=true)]
        public FileContentResult DownloadFileByPath(string path, string defaultPath = null)
        {
            if (IdentityHelper.GetCurrentIdentityUser() == null) return null;
            if (string.IsNullOrWhiteSpace(path) && string.IsNullOrWhiteSpace(defaultPath))
            {
                throw new ApplicationException("Please provide a path.");
            }
            return FileHelper.PendingDownloadInstance.DownloadByPath(path, defaultPath);
        }


        [Route("SaveListView")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult SaveListView()
        {
            var postedData = _ParsePostedData();
            return SaveListView(postedData, "DeliveryNoteForm");
        }


        [Route("DeleteListView")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult DeleteListView()
        {
            var postedData = _ParsePostedData();
            return DeleteListView(postedData, "DeliveryNoteForm");
        }


        [Route("LoadListViews")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult LoadListViews()
        {
            var postedData = _ParsePostedData();
            return LoadListViews(postedData, "DeliveryNoteForm");
        }



        #region Controller Actions
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName="AddDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("AddDeliveryNote")]
        public ActionResult AddDeliveryNote()

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "AddDeliveryNote";
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            return null;
        }

        [CustomControllerActionFilter(FillDropDownInitialValues=true, ActionName="AddDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("_API_AddDeliveryNote")]
        public ActionResult _API_AddDeliveryNote()

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "AddDeliveryNote";
            PushToHistory();
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            var _masterController = new DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.MasterPage.MasterPageController(@model);
            _masterController.ExecuteRender();
            var redirectInfo = ExecuteAddDeliveryNote();
            return redirectInfo;
        }

        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName="EditDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("EditDeliveryNote/{*id:int?}")]
        public ActionResult EditDeliveryNote(int? id)

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "EditDeliveryNote";
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            return null;
        }

        [CustomControllerActionFilter(FillDropDownInitialValues=true, ActionName="EditDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("_API_EditDeliveryNote/{*id:int?}")]
        public ActionResult _API_EditDeliveryNote(int? id)

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "EditDeliveryNote";
            PushToHistory();
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            var _masterController = new DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.MasterPage.MasterPageController(@model);
            _masterController.ExecuteRender();
            var redirectInfo = ExecuteEditDeliveryNote(id);
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="SaveDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("SaveDeliveryNote")]
        public ActionResult SaveDeliveryNote()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteSaveDeliveryNote();
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, ActionName="DeleteDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("DeleteDeliveryNote")]
        public ActionResult DeleteDeliveryNote()

        {
            var _data = _LoadViewModel();
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteDeleteDeliveryNote();
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, HasDefaultResultView=true, ActionName="NewDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("NewDeliveryNote/{*transactionId:int?}")]
        public ActionResult NewDeliveryNote(int? transactionId)

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "NewDeliveryNote";
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            return null;
        }

        [CustomControllerActionFilter(LogEnabled=true, FillDropDownInitialValues=true, ActionName="NewDeliveryNote", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("_API_NewDeliveryNote/{*transactionId:int?}")]
        public ActionResult _API_NewDeliveryNote(int? transactionId)

        {
            @model = new DeliveryNoteFormViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_DeliveryNoteForm"] = "NewDeliveryNote";
            PushToHistory();
            FileHelper.PendingUploadInstance.Clear("DeliveryNoteForm");
            FileHelper.PendingDownloadInstance.Clear("DeliveryNoteForm");
            var _masterController = new DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.MasterPage.MasterPageController(@model);
            _masterController.ExecuteRender();
            var redirectInfo = ExecuteNewDeliveryNote(transactionId);
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="OnOrderSelected", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("OnOrderSelected")]
        public ActionResult OnOrderSelected(System.Collections.Generic.List<DSS5_SupplyChainFinancialsOptimisation.BO.Order> orders)

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            if (!_redirectionFromSameController)
            {
                orders = DeserializeViewModelCollectionProperty<DSS5_SupplyChainFinancialsOptimisation.BO.Order, OrderDTO>(_data["orders"].ToString()).ToList();
            }
            var redirectInfo = ExecuteOnOrderSelected(orders);
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="InsertProducts", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("InsertProducts")]
        public ActionResult InsertProducts()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteInsertProducts();
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="ImportFromCSV", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("ImportFromCSV")]
        public ActionResult ImportFromCSV()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteImportFromCSV();
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="SubmitChanges", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("SubmitChanges")]
        public ActionResult SubmitChanges()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteSubmitChanges();
            return redirectInfo;
        }

        [CustomControllerActionFilter(LogEnabled=true, CausesValidation=true, ActionName="Exit", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("Exit")]
        public ActionResult Exit()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            FileHelper.PendingUploadInstance.UpdateModelWithFilesBinaryData("DeliveryNoteForm", @model);
            var redirectInfo = ExecuteExit();
            return redirectInfo;
        }

        #endregion
        #region Controller Actions Implementation
        /*<ControllerActionImplementation:AddDeliveryNote:1/>*/
        public ActionResult ExecuteAddDeliveryNote()
        {
            if (_parentController == null) _parentController = new MasterPage.MasterPageController(new  DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPage.MasterPageViewModel());
            ((MasterPage.MasterPageController) _parentController).ExecuteRender();
            ActionResult _result = null;
            @model.Title = "";
            return _result;
        }
        /*<ControllerActionImplementation:EditDeliveryNote:1/>*/
        public ActionResult ExecuteEditDeliveryNote(int? id)
        {
            if (_parentController == null) _parentController = new MasterPage.MasterPageController(new  DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPage.MasterPageViewModel());
            ((MasterPage.MasterPageController) _parentController).ExecuteRender();
            ActionResult _result = null;
            @model.DeliveryNote =  new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetById<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNote>(id);
            @model.Title = "";
            DSS5_SupplyChainFinancialsOptimisation.BO.Supplier sup = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Supplier>((s) => s.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
            if ((sup?.IsSupplier() ?? false))
            {
                @model.IsSupplier = true;
            }
            return _result;
        }
        /*<ControllerActionImplementation:SaveDeliveryNote:1/>*/
        public ActionResult ExecuteSaveDeliveryNote()
        {
            ActionResult _result = null;
            if (@model.DeliveryNote?.Transaction?.TransactionStatus == null)
            {
                @model.DeliveryNote.Transaction.TransactionStatus = new DSS5_SupplyChainFinancialsOptimisation.BO.TransactionStatus();
                @model.DeliveryNote.Transaction.TransactionStatus.Shipped = true;
                @model.DeliveryNote.Transaction.TransactionStatus.ShippedDateOccured = (@model.DeliveryNote?.DateIssued ?? System.Data.SqlTypes.SqlDateTime.MinValue.Value);
            }
            else
            {
                @model.DeliveryNote.Transaction.TransactionStatus.Shipped = true;
                @model.DeliveryNote.Transaction.TransactionStatus.ShippedDateOccured = (@model.DeliveryNote?.DateIssued ?? System.Data.SqlTypes.SqlDateTime.MinValue.Value);
            }
            foreach (var delNoteprod in @model.DeliveryNote?.DeliveryNoteProducts ?? Enumerable.Empty<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct>())
            {
                var _var0 = delNoteprod?.Code;
                if ((@model.DeliveryNote?.Transaction?.Supplier?.SupplierProducts?.Any((a) => a.Code == _var0) ?? false))
                {
                    zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Warning, "DeliveryNoteForm",  DSS5_SupplyChainFinancialsOptimisation.Hubs.EventsHub.RaiseDebugMessage, "product " + (delNoteprod?.Description ?? "") + "is already saved as a Supplier product.");
                }
                else
                {
                    DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct newSupplierProduct = new DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct();
                    newSupplierProduct.Code = (delNoteprod?.Code ?? "");
                    newSupplierProduct.Description = (delNoteprod?.Description ?? "");
                    newSupplierProduct.UnitValue = (delNoteprod?.UnitValue ?? "");
                    newSupplierProduct.MeasurementUnit = (delNoteprod?.MeasurementUnit ?? "");
                    newSupplierProduct.Price = (delNoteprod?.Price ?? 0);
                    newSupplierProduct.Supplier = @model.DeliveryNote?.Transaction?.Supplier;
                    @model.DeliveryNote?.Transaction?.Supplier?.AddSupplierProducts(newSupplierProduct);
                }
            }
            new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().Save<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNote>(@model.DeliveryNote);
            @model.Title = "";
            ClientCommand(ClientCommands.SHOW_MESSAGE, "Delivery Note saved successfully.");
            return _result;
        }
        /*<ControllerActionImplementation:DeleteDeliveryNote:1/>*/
        public ActionResult ExecuteDeleteDeliveryNote()
        {
            ActionResult _result = null;
            new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().DeleteDeliveryNote(@model.DeliveryNote);
            @model.Title = "";
            _result = CloseForm();
            return _result;
        }
        /*<ControllerActionImplementation:NewDeliveryNote:1/>*/
        public ActionResult ExecuteNewDeliveryNote(int? transactionId)
        {
            if (_parentController == null) _parentController = new MasterPage.MasterPageController(new  DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPage.MasterPageViewModel());
            ((MasterPage.MasterPageController) _parentController).ExecuteRender();
            ActionResult _result = null;
            @model.Title = "";
            @model.DeliveryNoteStandardPath = "DeliveryNoteStandard.csv";
            @model.DeliveryNoteStandardPhoto = "DeliveryNoteStandardPhoto.png";
            @model.UploadConfirmed = false;
            @model.DeliveryNote.Transaction =  new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetById<DSS5_SupplyChainFinancialsOptimisation.BO.Transaction>(transactionId);
            DSS5_SupplyChainFinancialsOptimisation.BO.Supplier sup = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Supplier>((s) => s.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
            if ((sup?.IsSupplier() ?? false))
            {
                @model.IsSupplier = true;
            }
            return _result;
        }
        /*<ControllerActionImplementation:OnOrderSelected:1/>*/
        public ActionResult ExecuteOnOrderSelected(System.Collections.Generic.List<DSS5_SupplyChainFinancialsOptimisation.BO.Order> orders)
        {
            ActionResult _result = null;
            System.Collections.Generic.List<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct> deliveryNoteProducts = new System.Collections.Generic.List<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct>();
            foreach (var ord in orders ?? Enumerable.Empty<DSS5_SupplyChainFinancialsOptimisation.BO.Order>())
            {
                foreach (var prod in ord?.OrderProducts ?? Enumerable.Empty<DSS5_SupplyChainFinancialsOptimisation.BO.OrderProduct>())
                {
                    DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct delProd = new DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct();
                    delProd.MeasurementUnit = (prod?.MeasurementUnit ?? "");
                    delProd.Price = (prod?.Price ?? 0);
                    delProd.Quantity = (prod?.Quantity ?? 0);
                    delProd.UnitValue = (prod?.UnitValue ?? "");
                    delProd.Code = (prod?.Code ?? "");
                    delProd.Description = (prod?.Description ?? "");
                    deliveryNoteProducts?.Add(delProd);
                }
            }
            @model.DeliveryNote.DeliveryNoteProducts = deliveryNoteProducts.ToList();
            @model.DeliveryNote.Orders = orders.ToList();
            return _result;
        }
        /*<ControllerActionImplementation:InsertProducts:1/>*/
        public ActionResult ExecuteInsertProducts()
        {
            ActionResult _result = null;
            foreach (var product in @model.SupplierProducts ?? Enumerable.Empty<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct>())
            {
                zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Warning, "DeliveryNoteForm",  DSS5_SupplyChainFinancialsOptimisation.Hubs.EventsHub.RaiseDebugMessage, "i am on change");
                DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct newProduct = new DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNoteProduct();
                newProduct.Description = (product?.Description ?? "");
                newProduct.Code = (product?.Code ?? "");
                newProduct.Price = (product?.Price ?? 0);
                newProduct.UnitValue = (product?.UnitValue ?? "");
                newProduct.MeasurementUnit = (product?.MeasurementUnit ?? "");
                @model.DeliveryNote?.AddDeliveryNoteProducts(newProduct);
            }
            return _result;
        }
        /*<ControllerActionImplementation:ImportFromCSV:1/>*/
        public ActionResult ExecuteImportFromCSV()
        {
            ActionResult _result = null;
            DSS5_SupplyChainFinancialsOptimisation.BO.Supplier supplier = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Supplier>((a) => a.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName())?.FirstOrDefault();
            if ((supplier != null && (supplier?.IsSupplier() ?? false)))
            {
                if ((supplier?.UserName == "Supplier25"))
                {
                    @model.DeliveryNote = DSS5_SupplyChainFinancialsOptimisation.BO.UtilsExtensions.LecosDeliveryNoteParser(@model.DeliveryNote, @model.CSVPath, (@model.DeliveryNote?.Transaction?.Id ?? 0));
                }
                if ((supplier?.UserName == "Supplier15"))
                {
                }
            }
            return _result;
        }
        /*<ControllerActionImplementation:SubmitChanges:1/>*/
        public ActionResult ExecuteSubmitChanges()
        {
            ActionResult _result = null;
            @model.UploadConfirmed = true;
            @model.DeliveryNote.Status = DSS5_SupplyChainFinancialsOptimisation.BO.Status.Initial;
            new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().Save<DSS5_SupplyChainFinancialsOptimisation.BO.DeliveryNote>(@model.DeliveryNote);
            return _result;
        }
        /*<ControllerActionImplementation:Exit:1/>*/
        public ActionResult ExecuteExit()
        {
            ActionResult _result = null;
            if ((zAppDev.DotNet.Framework.Utilities.Web.IsInControllerAction("NewDeliveryNote") && @model.DeliveryNote?.Status == DSS5_SupplyChainFinancialsOptimisation.BO.Status.Initial))
            {
                new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().DeleteDeliveryNote(@model.DeliveryNote);
                _result = CloseForm();
            }
            else
            {
                _result = CloseForm();
            }
            return _result;
        }
        #endregion
        #region Datasource controls
        /*<Datasource:SelectOrder:1/>*/
        /*<DataSourceFilter:SelectOrder:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order> Get_SelectOrder_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_SelectOrder_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order> Get_SelectOrder_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order>().AsQueryable();
            var _var0 = @model.DeliveryNote?.Transaction?.Id;
            return __items.Where(@this => @this.Transaction.Id == _var0);
        }


        /*<DataSourceGetFullRecordset:SelectOrder:1/>*/

        [HttpPost]
        [Route("SelectOrder_PickList_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "OrderDataSet", ClaimType = ClaimTypes.Dataset)]
        public JsonResult SelectOrder_PickList_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_SelectOrder_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new OrderDataSet_OrderDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(DeliveryNoteFormViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "SelectOrder");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:SelectOrder:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "OrderDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("SelectOrder_PickList_Datasource")]
        public JsonResult SelectOrder_PickList_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_SelectOrder_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_SelectOrder_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_SelectOrder_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_SelectOrder_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.Select(i => new OrderDataSet_OrderDTO(i, true)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.Select(i => new OrderDataSet_OrderDTO(i, true)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }

        /*<DataSourceAggregators:SelectOrder:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "OrderDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("SelectOrder_PickList_DatasourceAggregators")]
        public JsonResult SelectOrder_PickList_DatasourceAggregators()
        {
            object aggregatorsResponse = null;
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_SelectOrder_DatasourceQueryable(datasourceRequest);
            queryable = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            var formattings = new Dictionary<string, string>();
            if (datasourceRequest.GroupBy.Any()/* && datasourceRequest.GroupBy.First().GetGroupsClosed*/)
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData, true);
                GroupsHelper.FormatGroupedAggregators(groups, formattings);
                aggregatorsResponse = new ListResponse()
                {
                    Groups = groups
                };
            }
            else
            {
                var aggregatorsInfo = DeserializeAggregatorsRequest<DSS5_SupplyChainFinancialsOptimisation.BO.Order>(postedData["aggregatorsRequest"].ToString());
                var aggregators = RuntimePredicateBuilder.BuildAggregatorPredicates(aggregatorsInfo);
                foreach (var a in aggregators)
                {
                    var formatting = formattings.ContainsKey(a.Column) ? formattings[a.Column] : null;
                    a.Calculate(queryable, formatting);
                }
                aggregatorsResponse = aggregators;
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(aggregatorsResponse)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }




        /*<Datasource:PickList:1/>*/
        /*<DataSourceFilter:PickList:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct> Get_PickList_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_PickList_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct> Get_PickList_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct>().AsQueryable();
            var _var0 = zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName();
            return __items.Where(@this => @this.Supplier.UserName == _var0);
        }


        /*<DataSourceGetFullRecordset:PickList:1/>*/

        [HttpPost]
        [Route("PickList_PickList_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "SupplierProductDataSet", ClaimType = ClaimTypes.Dataset)]
        public JsonResult PickList_PickList_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_PickList_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new SupplierProductDataSet_SupplierProductDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(DeliveryNoteFormViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "PickList");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:PickList:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "SupplierProductDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("PickList_PickList_Datasource")]
        public JsonResult PickList_PickList_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_PickList_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_PickList_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_PickList_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_PickList_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.Select(i => new SupplierProductDataSet_SupplierProductDTO(i, true)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.Select(i => new SupplierProductDataSet_SupplierProductDTO(i, true)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }

        /*<DataSourceAggregators:PickList:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "SupplierProductDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("PickList_PickList_DatasourceAggregators")]
        public JsonResult PickList_PickList_DatasourceAggregators()
        {
            object aggregatorsResponse = null;
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_PickList_DatasourceQueryable(datasourceRequest);
            queryable = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            var formattings = new Dictionary<string, string>();
            if (datasourceRequest.GroupBy.Any()/* && datasourceRequest.GroupBy.First().GetGroupsClosed*/)
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData, true);
                GroupsHelper.FormatGroupedAggregators(groups, formattings);
                aggregatorsResponse = new ListResponse()
                {
                    Groups = groups
                };
            }
            else
            {
                var aggregatorsInfo = DeserializeAggregatorsRequest<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct>(postedData["aggregatorsRequest"].ToString());
                var aggregators = RuntimePredicateBuilder.BuildAggregatorPredicates(aggregatorsInfo);
                foreach (var a in aggregators)
                {
                    var formatting = formattings.ContainsKey(a.Column) ? formattings[a.Column] : null;
                    a.Calculate(queryable, formatting);
                }
                aggregatorsResponse = aggregators;
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(aggregatorsResponse)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }




        /*<Datasource:DeliveryNoteForm_OrderDataSet:1/>*/
        /*<DataSourceFilter:DeliveryNoteForm_OrderDataSet:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order> Get_DeliveryNoteForm_OrderDataSet_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_DeliveryNoteForm_OrderDataSet_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order> Get_DeliveryNoteForm_OrderDataSet_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.Order>().AsQueryable();
            var _var0 = @model.DeliveryNote?.Transaction?.Id;
            return __items.Where(@this => @this.Transaction.Id == _var0);
        }


        /*<DataSourceGetFullRecordset:DeliveryNoteForm_OrderDataSet:1/>*/

        [HttpPost]
        [Route("DeliveryNoteForm_OrderDataSet_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "OrderDataSet", ClaimType = ClaimTypes.Dataset)]
        public JsonResult DeliveryNoteForm_OrderDataSet_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_DeliveryNoteForm_OrderDataSet_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new OrderDataSet_OrderDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(DeliveryNoteFormViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "DeliveryNoteForm_OrderDataSet");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:DeliveryNoteForm_OrderDataSet:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "OrderDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("DeliveryNoteForm_OrderDataSet_Datasource")]
        public JsonResult DeliveryNoteForm_OrderDataSet_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_DeliveryNoteForm_OrderDataSet_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_OrderDataSet_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_OrderDataSet_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_OrderDataSet_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            var _dto = DynamicDtoInfo.CreateFromPropsArray(datasourceRequest.DtoProperties);
            var _convertionMethod = _dto.GetConvertionFunc<DSS5_SupplyChainFinancialsOptimisation.BO.Order>();
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }


        /*<Datasource:DeliveryNoteForm_SupplierProductDataSet:1/>*/
        /*<DataSourceFilter:DeliveryNoteForm_SupplierProductDataSet:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct> Get_DeliveryNoteForm_SupplierProductDataSet_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_DeliveryNoteForm_SupplierProductDataSet_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct> Get_DeliveryNoteForm_SupplierProductDataSet_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct>().AsQueryable();
            var _var0 = zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName();
            return __items.Where(@this => @this.Supplier.UserName == _var0);
        }


        /*<DataSourceGetFullRecordset:DeliveryNoteForm_SupplierProductDataSet:1/>*/

        [HttpPost]
        [Route("DeliveryNoteForm_SupplierProductDataSet_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "SupplierProductDataSet", ClaimType = ClaimTypes.Dataset)]
        public JsonResult DeliveryNoteForm_SupplierProductDataSet_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_DeliveryNoteForm_SupplierProductDataSet_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new SupplierProductDataSet_SupplierProductDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(DeliveryNoteFormViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "DeliveryNoteForm_SupplierProductDataSet");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:DeliveryNoteForm_SupplierProductDataSet:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "SupplierProductDataSet", ClaimType = ClaimTypes.Dataset)]
        [Route("DeliveryNoteForm_SupplierProductDataSet_Datasource")]
        public JsonResult DeliveryNoteForm_SupplierProductDataSet_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_DeliveryNoteForm_SupplierProductDataSet_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_SupplierProductDataSet_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_SupplierProductDataSet_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_DeliveryNoteForm_SupplierProductDataSet_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            var _dto = DynamicDtoInfo.CreateFromPropsArray(datasourceRequest.DtoProperties);
            var _convertionMethod = _dto.GetConvertionFunc<DSS5_SupplyChainFinancialsOptimisation.BO.SupplierProduct>();
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }


        #endregion

        #region ImageBox controls


        private Func<object, int[], string> Get_ImageBox_RelativePath
        {
            get
            {
                return (object _model, int[] indexes) =>
                {
                    var @model = _model as DeliveryNoteFormViewModel;
                    return zAppDev.DotNet.Framework.Utilities.Web.MapPath(System.IO.Path.Combine("~/App_Data", "Photos"))  + "/" +  Path.GetFileName(@model.DeliveryNoteStandardPhoto);
                };
            }
        }

        [HttpPost]
        [Route("ImageBox_Download")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult ImageBox_Download()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            try
            {
                var data = FileHelper.DownloadFromFileSystemAsBase64(Get_ImageBox_RelativePath, @model, indexes);
                return Content(data);
            }
            catch (Exception e)
            {
                _logger.Error("Could not download Image 'ImageBox'", e);
                return Content(null);
            }
        }


        #endregion

        #region File Attachment controls

        private Func<object, int[], string> Get_FileAttachmentDNote_RelativePath
        {
            get
            {
                return (object _model, int[] indexes) =>
                {
                    var @model = _model as DeliveryNoteFormViewModel;
                    return  Path.GetFileName(@model.DeliveryNote.DNoteAttachment);
                };
            }
        }

        [HttpPost]
        [Route("FileAttachmentDNote_Download")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachmentDNote_Download()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var key = "";
            var pending = FileHelper.PendingUploadInstance.Get("DeliveryNoteForm", "FileAttachmentDNote", indexes);
            if (pending == null)
            {
                try
                {
                    key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", Get_FileAttachmentDNote_RelativePath, @model, indexes);
                }
                catch (Exception x)
                {
                    _logger.Error($"Download failed. Possibly file not found. Control 'FileAttachmentDNote'", x);
                    return Content(null);
                }
            }
            else
            {
                var relativeTargetPath = Get_FileAttachmentDNote_RelativePath.Invoke(@model, indexes);
                var fileName = Path.GetFileName(relativeTargetPath);
                key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", pending.BinaryContents, fileName);
            }
            return Content(key);
        }

        [HttpPost]
        [Route("FileAttachmentDNote_Upload")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachmentDNote_Upload()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var __pendingFile = ExecuteFileAttachmentDNote_Upload(indexes, HttpContext.Request.Files);
            var _result = Json(new
            {
                Legacy = true,
                Type = "FileUpload" ,

                Data = new
                {
                    FileName = @model.DeliveryNote.DNoteAttachment
                }

            }, JsonRequestBehavior.AllowGet);
            _result.MaxJsonLength = int.MaxValue;
            return _result;
        }

        public FileHelper.UploadInfo ExecuteFileAttachmentDNote_Upload(int[] indexes, HttpFileCollectionBase files)
        {
            var file = files[0];
            var pendingFile = new FileHelper.UploadInfo(file, "DeliveryNoteForm", "FileAttachmentDNote", indexes);
            pendingFile.GetRelativePath = Get_FileAttachmentDNote_RelativePath;
            @model.DeliveryNote.DNoteAttachment = FileHelper.GetUtf8SafeFilename(file.FileName);
            IsDirty = true;
            FileHelper.PendingUploadInstance.Add(pendingFile);
            return pendingFile;
        }

        [HttpPost]
        [Route("FileAttachmentDNote_Remove")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachmentDNote_Remove()
        {
            var postedData = _LoadViewModel();
            var removedAutomatically = postedData["removedAutomatically"]?.ToString() == true.ToString();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var pending = FileHelper.PendingUploadInstance.Get("DeliveryNoteForm", "FileAttachmentDNote", indexes);
            if (pending != null)
            {
                try
                {
                    FileHelper.PendingUploadInstance.RemoveByKey("DeliveryNoteForm", "FileAttachmentDNote", indexes);
                }
                catch (Exception x)
                {
                    _logger.Error($"Removing uploaded file failed. Possibly file not found. Control 'FileAttachmentDNote'", x);
                    return Content(null);
                }
            }
            if (removedAutomatically) return Content(null); // Usually removed when user deletes grid row. No need to update model
            @model.DeliveryNote.DNoteAttachment = null;
            IsDirty = true;
            viewDTO.Model = new DeliveryNoteFormViewModelDTO(@model);
            var _result = Json(new
            {
                Type = "Data",
                Data = viewDTO.Serialize()
            }, JsonRequestBehavior.AllowGet);
            _result.MaxJsonLength = int.MaxValue;
            return _result;
        }

        private Func<object, int[], string> Get_FileAttachment_RelativePath
        {
            get
            {
                return (object _model, int[] indexes) =>
                {
                    var @model = _model as DeliveryNoteFormViewModel;
                    return  Path.GetFileName(@model.CSVPath);
                };
            }
        }

        [HttpPost]
        [Route("FileAttachment_Download")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachment_Download()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var key = "";
            var pending = FileHelper.PendingUploadInstance.Get("DeliveryNoteForm", "FileAttachment", indexes);
            if (pending == null)
            {
                try
                {
                    key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", Get_FileAttachment_RelativePath, @model, indexes);
                }
                catch (Exception x)
                {
                    _logger.Error($"Download failed. Possibly file not found. Control 'FileAttachment'", x);
                    return Content(null);
                }
            }
            else
            {
                var relativeTargetPath = Get_FileAttachment_RelativePath.Invoke(@model, indexes);
                var fileName = Path.GetFileName(relativeTargetPath);
                key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", pending.BinaryContents, fileName);
            }
            return Content(key);
        }

        [HttpPost]
        [Route("FileAttachment_Upload")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachment_Upload()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var __pendingFile = ExecuteFileAttachment_Upload(indexes, HttpContext.Request.Files);
            var _result = Json(new
            {
                Legacy = true,
                Type = "FileUpload" ,

                Data = new
                {
                    FileName = @model.CSVPath
                }

            }, JsonRequestBehavior.AllowGet);
            _result.MaxJsonLength = int.MaxValue;
            return _result;
        }

        public FileHelper.UploadInfo ExecuteFileAttachment_Upload(int[] indexes, HttpFileCollectionBase files)
        {
            var file = files[0];
            var pendingFile = new FileHelper.UploadInfo(file, "DeliveryNoteForm", "FileAttachment", indexes);
            pendingFile.GetRelativePath = Get_FileAttachment_RelativePath;
            @model.CSVPath = FileHelper.GetUtf8SafeFilename(file.FileName);
            IsDirty = true;
            FileHelper.PendingUploadInstance.Add(pendingFile);
            return pendingFile;
        }

        [HttpPost]
        [Route("FileAttachment_Remove")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachment_Remove()
        {
            var postedData = _LoadViewModel();
            var removedAutomatically = postedData["removedAutomatically"]?.ToString() == true.ToString();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var pending = FileHelper.PendingUploadInstance.Get("DeliveryNoteForm", "FileAttachment", indexes);
            if (pending != null)
            {
                try
                {
                    FileHelper.PendingUploadInstance.RemoveByKey("DeliveryNoteForm", "FileAttachment", indexes);
                }
                catch (Exception x)
                {
                    _logger.Error($"Removing uploaded file failed. Possibly file not found. Control 'FileAttachment'", x);
                    return Content(null);
                }
            }
            if (removedAutomatically) return Content(null); // Usually removed when user deletes grid row. No need to update model
            @model.CSVPath = null;
            IsDirty = true;
            viewDTO.Model = new DeliveryNoteFormViewModelDTO(@model);
            var _result = Json(new
            {
                Type = "Data",
                Data = viewDTO.Serialize()
            }, JsonRequestBehavior.AllowGet);
            _result.MaxJsonLength = int.MaxValue;
            return _result;
        }

        private Func<object, int[], string> Get_FileAttachment1_RelativePath
        {
            get
            {
                return (object _model, int[] indexes) =>
                {
                    var @model = _model as DeliveryNoteFormViewModel;
                    return zAppDev.DotNet.Framework.Utilities.Web.MapPath(System.IO.Path.Combine("~/App_Data", "Standards"))  + "/" +  Path.GetFileName(@model.DeliveryNoteStandardPath);
                };
            }
        }

        [HttpPost]
        [Route("FileAttachment1_Download")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult FileAttachment1_Download()
        {
            var postedData = _LoadViewModel();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var key = "";
            var pending = FileHelper.PendingUploadInstance.Get("DeliveryNoteForm", "FileAttachment1", indexes);
            if (pending == null)
            {
                try
                {
                    key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", Get_FileAttachment1_RelativePath, @model, indexes);
                }
                catch (Exception x)
                {
                    _logger.Error($"Download failed. Possibly file not found. Control 'FileAttachment1'", x);
                    return Content(null);
                }
            }
            else
            {
                var relativeTargetPath = Get_FileAttachment1_RelativePath.Invoke(@model, indexes);
                var fileName = Path.GetFileName(relativeTargetPath);
                key = FileHelper.PendingDownloadInstance.Add("DeliveryNoteForm", pending.BinaryContents, fileName);
            }
            return Content(key);
        }
        #endregion

        public override ActionResult PreActionFilterHook(bool causesValidation, bool listenToEvent, string actionName)
        {
            System.Web.HttpContext.Current.Items["_currentControllerAction"] = actionName;
            if (listenToEvent) return null;
            return null;
        }
        public override ActionResult PostActionFilterHook(bool hasDefaultResultView, bool fillDropDownInitialValues = false)
        {
            if (HasClientResponse())
            {
                viewDTO.ClientResponse = GetClientResponse();
            }
            else
            {
                var _modelDTO = new DeliveryNoteFormViewModelDTO(@model);
                viewDTO.Model = _modelDTO;
            }
            if (!hasDefaultResultView)
            {
                var __result = Json(new
                {
                    Type = "Data",Data = viewDTO.Serialize()
                }, JsonRequestBehavior.AllowGet);
                __result.MaxJsonLength = int.MaxValue;
                return __result;
            }
            return View("DeliveryNoteForm");
        }

        #region Data Validations


        private ActionResult GetFailedDataValidationsResult()
        {
            try
            {
                RunDataValidations();
                if (!viewDTO.DataValidationsHaveFailed) return null;
                var __result = Json(new
                {
                    Type = "RuleEvaluation",Data = viewDTO.Serialize()
                }, JsonRequestBehavior.AllowGet);
                __result.MaxJsonLength = int.MaxValue;
                return __result;
            }
            catch (Exception e)
            {
                _logger.Error("!!! DANGER: Error while evaluating Data Validations !!!", e);
                log4net.LogManager.GetLogger(this.GetType()).Error("Form: DeliveryNoteForm, Action: " + System.Web.HttpContext.Current.Items["_currentControllerAction"], e);
                //throw;
                return null;
            }
        }
        public List<RuleResult> RunDataValidations()
        {
            var masterPageDataValidations = (_parentController as Controllers.MasterPage.MasterPageController).RunDataValidations();
            if (masterPageDataValidations?.Any() == true)
            {
                viewDTO.RuleEvaluations.DataValidations.AddRange(masterPageDataValidations);
            }
            return viewDTO.RuleEvaluations.DataValidations;
        }

        #endregion
    }
}
