// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using AppCode;
using DSS5_SupplyChainFinancialsOptimisation.BO;
using DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.LetterOfCreditList;
using Identity = zAppDev.DotNet.Framework.Identity;
using log4net;
using Newtonsoft.Json;
using NHibernate.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Identity;
using zAppDev.DotNet.Framework.Identity.Model;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Mvc;
using zAppDev.DotNet.Framework.Utilities;

namespace DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.LetterOfCreditList
{

    [RoutePrefix("LetterOfCreditList")]
    public class LetterOfCreditListController : ControllerBase<LetterOfCreditListViewModel, LetterOfCreditListViewModelDTO>
    {

        /*<Form:LetterOfCreditList:0/>*/
        public LetterOfCreditListController()
        {
            _logger = log4net.LogManager.GetLogger(typeof(LetterOfCreditListController));
            if (ViewModelDTOBase.DTOHelper == null)
            {
                ViewModelDTOBase.DTOHelper = new DTOHelper();
            }
        }

        protected override void ViewModelLoaded()
        {
            var masterViewModel = new DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPageForLists.MasterPageForListsViewModel
            {
                Title = model.Title, Version = model.Version
            };
            _parentController = new MasterPageForLists.MasterPageForListsController(masterViewModel);
            _parentController.IsDirty = IsDirty;
        }

        public void SetModel(LetterOfCreditListViewModel m)
        {
            @model = m;
        }


        public override void CommitAllFiles()
        {
        }

        public override void CommitAllFilesLegacy()
        {
        }

        public override void ClearPendingFiles()
        {
        }






        [HttpGet]

        [Route("GetViewDTO")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ContentResult GetViewDTO(int hash)
        {
            return Content(GetViewFromViewDTOsDicSerialized(hash));
        }

        [HttpPost]

        [Route("UpdateInstance")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult UpdateInstance()
        {
            return PrepareUpdateInstanceResult(typeof(LetterOfCreditListViewModel));
        }

        [HttpPost]

        [Route("_Raise")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public ActionResult _Raise()
        {
            return _RaiseEvent();
        }

        [HttpGet]
        [Route("DownloadFile")]
        [CustomControllerActionFilter(HasDefaultResultView=true)]
        public FileContentResult DownloadFile(string id)
        {
            return FileHelper.PendingDownloadInstance.DownloadByKey("LetterOfCreditList", id);
        }

        [HttpGet]
        [Route("DownloadFileByPath")]
        [CustomControllerActionFilter(HasDefaultResultView=true)]
        public FileContentResult DownloadFileByPath(string path, string defaultPath = null)
        {
            if (IdentityHelper.GetCurrentIdentityUser() == null) return null;
            if (string.IsNullOrWhiteSpace(path) && string.IsNullOrWhiteSpace(defaultPath))
            {
                throw new ApplicationException("Please provide a path.");
            }
            return FileHelper.PendingDownloadInstance.DownloadByPath(path, defaultPath);
        }


        [Route("SaveListView")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult SaveListView()
        {
            var postedData = _ParsePostedData();
            return SaveListView(postedData, "LetterOfCreditList");
        }


        [Route("DeleteListView")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult DeleteListView()
        {
            var postedData = _ParsePostedData();
            return DeleteListView(postedData, "LetterOfCreditList");
        }


        [Route("LoadListViews")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult LoadListViews()
        {
            var postedData = _ParsePostedData();
            return LoadListViews(postedData, "LetterOfCreditList");
        }



        #region Controller Actions
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName="Retrieve", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("Retrieve")]
        public ActionResult Retrieve()

        {
            @model = new LetterOfCreditListViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_LetterOfCreditList"] = "Retrieve";
            return null;
        }

        [CustomControllerActionFilter(FillDropDownInitialValues=true, ActionName="Retrieve", ClaimType = ClaimTypes.ControllerAction)]
        [HttpGet]
        [Route("_API_Retrieve")]
        public ActionResult _API_Retrieve()

        {
            @model = new LetterOfCreditListViewModel();
            System.Web.HttpContext.Current.Session["LastEntryPoint_LetterOfCreditList"] = "Retrieve";
            PushToHistory();
            var _masterController = new DSS5_SupplyChainFinancialsOptimisation.UI.Controllers.MasterPageForLists.MasterPageForListsController(@model);
            _masterController.ExecuteRender();
            var redirectInfo = ExecuteRetrieve();
            return redirectInfo;
        }

        [CustomControllerActionFilter(CausesValidation=true, ActionName="DeleteSeclected", ClaimType = ClaimTypes.ControllerAction)]
        [HttpPost]
        [Route("DeleteSeclected")]
        public ActionResult DeleteSeclected()

        {
            var _data = _LoadViewModel();
            var _failedValidationsResult = GetFailedDataValidationsResult();
            if (_failedValidationsResult != null) return _failedValidationsResult;
            var redirectInfo = ExecuteDeleteSeclected();
            return redirectInfo;
        }

        #endregion
        #region Controller Actions Implementation
        /*<ControllerActionImplementation:Retrieve:1/>*/
        public ActionResult ExecuteRetrieve()
        {
            if (_parentController == null) _parentController = new MasterPageForLists.MasterPageForListsController(new  DSS5_SupplyChainFinancialsOptimisation.UI.ViewModels.MasterPageForLists.MasterPageForListsViewModel());
            ((MasterPageForLists.MasterPageForListsController) _parentController).ExecuteRender();
            ActionResult _result = null;
            @model.Title = "";
            return _result;
        }
        /*<ControllerActionImplementation:DeleteSeclected:1/>*/
        public ActionResult ExecuteDeleteSeclected()
        {
            ActionResult _result = null;
            foreach (var letterOfCredit in SelectedItemInfo<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>.GetSelectedItems(Get_LetterOfCreditListNoDT_DatasourceQueryable(null, false), @model.LetterOfCreditListNoDTSelectedItems) ?? Enumerable.Empty<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>())
            {
                new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().DeleteLetterOfCredit(letterOfCredit);
            }
            ClientCommand(ClientCommands.DATALIST_REFRESH, "LetterOfCreditListNoDT");
            ClientCommand(ClientCommands.SHOW_MESSAGE, "Deleted Selected Letter Of Credits successfully!");
            return _result;
        }
        #endregion
        #region Datasource controls
        /*<Datasource:LetterOfCreditListNoDT:1/>*/
        /*<DataSourceFilter:LetterOfCreditListNoDT:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit> Get_LetterOfCreditListNoDT_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_LetterOfCreditListNoDT_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit> Get_LetterOfCreditListNoDT_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>().AsQueryable();
            var _var0 = zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName();
            return __items.Where(@this => @this.Transaction.Supplier.UserName == _var0);
        }


        /*<DataSourceGetFullRecordset:LetterOfCreditListNoDT:1/>*/

        [HttpPost]
        [Route("LetterOfCreditListNoDT_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "LetterOfCredit", ClaimType = ClaimTypes.Dataset)]
        public JsonResult LetterOfCreditListNoDT_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_LetterOfCreditListNoDT_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new LetterOfCredit_LetterOfCreditDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(LetterOfCreditListViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "LetterOfCreditListNoDT");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:LetterOfCreditListNoDT:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "LetterOfCredit", ClaimType = ClaimTypes.Dataset)]
        [Route("LetterOfCreditListNoDT_Datasource")]
        public JsonResult LetterOfCreditListNoDT_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_LetterOfCreditListNoDT_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditListNoDT_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditListNoDT_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditListNoDT_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.Select(i => new LetterOfCredit_LetterOfCreditDTO(i, true)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.Select(i => new LetterOfCredit_LetterOfCreditDTO(i, true)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }

        /*<DataSourceAggregators:LetterOfCreditListNoDT:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "LetterOfCredit", ClaimType = ClaimTypes.Dataset)]
        [Route("LetterOfCreditListNoDT_DatasourceAggregators")]
        public JsonResult LetterOfCreditListNoDT_DatasourceAggregators()
        {
            object aggregatorsResponse = null;
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_LetterOfCreditListNoDT_DatasourceQueryable(datasourceRequest);
            queryable = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            var formattings = new Dictionary<string, string>();
            formattings.Add("ValueOfLoC", "#,0.00;'-'#,0.00;'0'");
            formattings.Add("DateOfValidity", "dd/MM/yyyy");
            formattings.Add("DateOfExpiry", "dd/MM/yyyy");
            formattings.Add("Calculated", "#,0.00;'-'#,0.00;'0'");
            if (datasourceRequest.GroupBy.Any()/* && datasourceRequest.GroupBy.First().GetGroupsClosed*/)
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData, true);
                GroupsHelper.FormatGroupedAggregators(groups, formattings);
                aggregatorsResponse = new ListResponse()
                {
                    Groups = groups
                };
            }
            else
            {
                var aggregatorsInfo = DeserializeAggregatorsRequest<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>(postedData["aggregatorsRequest"].ToString());
                var aggregators = RuntimePredicateBuilder.BuildAggregatorPredicates(aggregatorsInfo);
                foreach (var a in aggregators)
                {
                    var formatting = formattings.ContainsKey(a.Column) ? formattings[a.Column] : null;
                    a.Calculate(queryable, formatting);
                }
                aggregatorsResponse = aggregators;
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(aggregatorsResponse)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }




        [Route("LetterOfCreditListNoDT_Export")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult LetterOfCreditListNoDT_Export()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"]?.ToString());
            var exportOptions = ExportHelper.ParseExportOptions(postedData);
            var aggregatorsInfo = DeserializeAggregatorsRequest<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>(exportOptions.AggregatorsRequest);
            var downloadKey = LetterOfCreditListNoDT_ExportImplementation(datasourceRequest, exportOptions, aggregatorsInfo);
            var __result = Json(new
            {
                Data = downloadKey
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }

        [NonAction]
        public string LetterOfCreditListNoDT_ExportImplementation(DatasourceRequest datasourceRequest, ExportHelper.ExportOptions exportOptions, List<AggregatorInfo<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>> aggregatorsInfo)
        {
            if (exportOptions.Range == ExportHelper.Range.TOP100)
            {
                datasourceRequest.StartRow = 0;
                datasourceRequest.PageSize = 100;
            }
            else if (exportOptions.Range == ExportHelper.Range.ALL)
            {
                datasourceRequest.StartRow = 0;
                datasourceRequest.PageSize = int.MaxValue;
            }
            if (string.IsNullOrWhiteSpace(exportOptions.Filename))
            {
                exportOptions.Filename = "LetterOfCreditListNoDT";
            }
            if (exportOptions.ColumnOptions == null)
            {
                exportOptions.ColumnOptions = new List<ExportHelper.ColumnOptions>
                {
                    new ExportHelper.ColumnOptions { Column = "Id", IsVisible = true },
                    new ExportHelper.ColumnOptions { Column = "ValueOfLoC", IsVisible = true },
                    new ExportHelper.ColumnOptions { Column = "DateOfValidity", IsVisible = true },
                    new ExportHelper.ColumnOptions { Column = "DateOfExpiry", IsVisible = true },
                    new ExportHelper.ColumnOptions { Column = "Calculated", IsVisible = true },

                };
            }
            var queryable = Get_LetterOfCreditListNoDT_DatasourceQueryable(datasourceRequest);
            var totalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count();
            var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
            var dto = items.Select(i => new LetterOfCredit_LetterOfCreditDTO(i));
            var formattings = new Dictionary<string, string>();
            formattings.Add("ValueOfLoC", "#,0.00;'-'#,0.00;'0'");
            formattings.Add("DateOfValidity", "dd/MM/yyyy");
            formattings.Add("DateOfExpiry", "dd/MM/yyyy");
            formattings.Add("Calculated", "#,0.00;'-'#,0.00;'0'");
            var aggregators = RuntimePredicateBuilder.BuildAggregatorPredicates(aggregatorsInfo);
            foreach (var a in aggregators)
            {
                var formatting = formattings.ContainsKey(a.Column) ? formattings[a.Column] : null;
                a.Calculate(queryable, formatting);
            }
            var exportDataDTO = new List<ExportHelper.ExportRecordDTO>();
            foreach (var record in dto)
            {
                var recordDTO = new ExportHelper.ExportRecordDTO();
                recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                {
                    ColumnName = nameof(record.Id),
                    Value = record?.Id,
                    ColumnDataType = "int",
                    Format = "",
                    ExcelFormat = @"",
                    Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_Id")
                });
                recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                {
                    ColumnName = nameof(record.ValueOfLoC),
                    Value = record?.ValueOfLoC,
                    ColumnDataType = "decimal",
                    Format = "#,0.00;'-'#,0.00;'0'",
                    ExcelFormat = @"#,##0.00;-#,##0.00;#,##0.00",
                    Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_ValueOfLoC")
                });
                recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                {
                    ColumnName = nameof(record.DateOfValidity),
                    Value = record?.DateOfValidity,
                    ColumnDataType = "DateTime",
                    Format = "dd/MM/yyyy",
                    ExcelFormat = @"dd/MM/yyyy",
                    Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_DateOfValidity")
                });
                recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                {
                    ColumnName = nameof(record.DateOfExpiry),
                    Value = record?.DateOfExpiry,
                    ColumnDataType = "DateTime",
                    Format = "dd/MM/yyyy",
                    ExcelFormat = @"dd/MM/yyyy",
                    Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_DateOfExpiry")
                });
                recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                {
                    ColumnName = nameof(record.Calculated),
                    Value = record?.Calculated,
                    ColumnDataType = "decimal",
                    Format = "#,0.00;'-'#,0.00;'0'",
                    ExcelFormat = @"#,##0.00;-#,##0.00;#,##0.00",
                    Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_Calculated")
                });
                exportDataDTO.Add(recordDTO);
            }
            if (aggregators.Count > 0)
            {
                foreach (AggregatorType aggregatorType in Enum.GetValues(typeof(AggregatorType)))
                {
                    var emptyAggregatorRow = true;
                    var recordDTO = new ExportHelper.ExportRecordDTO();
                    foreach (var columnOption in exportOptions.ColumnOptions)
                    {
                        var aggregatorValue = "";
                        switch (aggregatorType)
                        {
                        case AggregatorType.COUNT:
                            if (columnOption.CountIsVisible)
                            {
                                var averageAggregator = aggregators.SingleOrDefault(agg => agg.Column == columnOption.Column && agg.Type == AggregatorType.COUNT);
                                aggregatorValue = $"{BaseViewPage<object>.GetResourceValue("GlobalResources", "RES_DATALIST_AGGREGATORS_GrandCount")} {averageAggregator?.ValueFormatted}";
                                emptyAggregatorRow = false;
                            }
                            break;
                        case AggregatorType.SUM:
                            if (columnOption.SumIsVisible)
                            {
                                var averageAggregator = aggregators.SingleOrDefault(agg => agg.Column == columnOption.Column && agg.Type == AggregatorType.SUM);
                                aggregatorValue = $"{BaseViewPage<object>.GetResourceValue("GlobalResources", "RES_DATALIST_AGGREGATORS_GrandTotal")} {averageAggregator?.ValueFormatted}";
                                emptyAggregatorRow = false;
                            }
                            break;
                        case AggregatorType.AVERAGE:
                            if (columnOption.AverageIsVisible)
                            {
                                var averageAggregator = aggregators.SingleOrDefault(agg => agg.Column == columnOption.Column && agg.Type == AggregatorType.AVERAGE);
                                aggregatorValue += $"{BaseViewPage<object>.GetResourceValue("GlobalResources", "RES_DATALIST_AGGREGATORS_GrandAverage")} {averageAggregator?.ValueFormatted}";
                                emptyAggregatorRow = false;
                            }
                            break;
                        }
                        recordDTO.Columns.Add(new ExportHelper.ExportColumnDTO
                        {
                            ColumnName = columnOption.Column,
                            Value = aggregatorValue,
                            ColumnDataType = "string",
                            Format = ""
                        });
                    }
                    if (!emptyAggregatorRow)
                    {
                        exportDataDTO.Add(recordDTO);
                    }
                }
            }
            var path = ExportHelper.ExportList(exportDataDTO, exportOptions, totalRows);
            var content = System.IO.File.ReadAllBytes(Path.Combine(Path.GetTempPath(), path));
            var fileName = Path.GetFileName(path);
            return FileHelper.PendingDownloadInstance.Add("LetterOfCreditList", content, fileName);
        }

        [Route("LetterOfCreditListNoDT_ExportV2")]
        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "GeneralOperation", ClaimType = ClaimTypes.GenericAction)]
        public JsonResult LetterOfCreditListNoDT_ExportV2()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var exportOptions = Utilities.Deserialize<ExportOptionsV2>(postedData["exportData"]?.ToString());
            var aggregatorsInfo = DeserializeAggregatorsRequest<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>(postedData["aggregatorsRequest"]?.ToString());
            var downloadKey = LetterOfCreditListNoDT_ExportV2Implementation(datasourceRequest, exportOptions, aggregatorsInfo);
            var __result = Json(new
            {
                Data = downloadKey
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }

        [NonAction]
        public string LetterOfCreditListNoDT_ExportV2Implementation(DatasourceRequest datasourceRequest, ExportOptionsV2 exportOptions, List<AggregatorInfo<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>> aggregatorsInfo)
        {
            var watch = System.Diagnostics.Stopwatch.StartNew();
            long elapsedMilliseconds = 0;
            switch (exportOptions.Range)
            {
            case ExportHelper.Range.ALL:
                datasourceRequest.StartRow = 0;
                datasourceRequest.PageSize = int.MaxValue;
                break;
            case ExportHelper.Range.TOP100:
                datasourceRequest.StartRow = 0;
                datasourceRequest.PageSize = 100;
                break;
            }
            var queryable = Get_LetterOfCreditListNoDT_DatasourceQueryable(datasourceRequest);
            var formattings = new Dictionary<string, string>();
            var path = "";
            var exportHelper = new ExportHelperV2<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>(exportOptions, new Dictionary<string, Func<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit, object>>
            {
                {"Id" , item => item?.Id }, {"ValueOfLoC" , item => item?.ValueOfLoC }, {"DateOfValidity" , item => item?.DateOfValidity }, {"DateOfExpiry" , item => item?.DateOfExpiry }, {"Calculated" , item => item?.Calculated },
            });
            if (exportHelper.Options.ColumnInfo == null)
            {
                exportHelper.Options.ColumnInfo = new List<ColumnOptionsV2>
                {
                    new ColumnOptionsV2 { Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_Id"), Formatting = "", Name = "Id", ExcelFormat = @"" },
                    new ColumnOptionsV2 { Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_ValueOfLoC"), Formatting = "#,0.00;'-'#,0.00;'0'", Name = "ValueOfLoC", ExcelFormat = @"#,##0.00;-#,##0.00;#,##0.00" },
                    new ColumnOptionsV2 { Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_DateOfValidity"), Formatting = "dd/MM/yyyy", Name = "DateOfValidity", ExcelFormat = @"dd/MM/yyyy" },
                    new ColumnOptionsV2 { Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_DateOfExpiry"), Formatting = "dd/MM/yyyy", Name = "DateOfExpiry", ExcelFormat = @"dd/MM/yyyy" },
                    new ColumnOptionsV2 { Caption = BaseViewPage<object>.GetResourceValue("LetterOfCreditList", "RES_LIST_LetterOfCreditListNoDT_COLUMN_Calculated"), Formatting = "#,0.00;'-'#,0.00;'0'", Name = "Calculated", ExcelFormat = @"#,##0.00;-#,##0.00;#,##0.00" },

                };
            }
            if (string.IsNullOrWhiteSpace(exportHelper.Options.Filename))
            {
                exportHelper.Options.Filename = "LetterOfCreditListNoDT";
            }
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, aggregatorsInfo);
                var aggregators = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, aggregatorsInfo, true);
                GroupsHelper.FormatGroupedAggregators(aggregators, formattings);
                watch.Stop();
                elapsedMilliseconds = watch.ElapsedMilliseconds;
                _logger.Info($"ExportV2 Performance: LetterOfCreditListNoDT export query with grouping and range {exportOptions.Range} took {elapsedMilliseconds}ms");
                watch.Restart();
                path = exportHelper.Export(groups, aggregators);
                watch.Stop();
                elapsedMilliseconds += watch.ElapsedMilliseconds;
                _logger.Info($"ExportV2 Performance: LetterOfCreditListNoDT export to excel with grouping and range {exportOptions.Range} took {watch.ElapsedMilliseconds}ms");
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                var aggregators = RuntimePredicateBuilder.BuildAggregatorPredicates(aggregatorsInfo);
                foreach (var a in aggregators)
                {
                    var formatting = formattings.ContainsKey(a.Column) ? formattings[a.Column] : null;
                    a.Calculate(queryable, formatting);
                }
                var loadedItems = items.ToList();
                watch.Stop();
                elapsedMilliseconds = watch.ElapsedMilliseconds;
                _logger.Info($"ExportV2 Performance: LetterOfCreditListNoDT export query with range {exportOptions.Range} took {elapsedMilliseconds}ms");
                watch.Restart();
                path = exportHelper.Export(loadedItems, aggregators);
                watch.Stop();
                elapsedMilliseconds += watch.ElapsedMilliseconds;
                _logger.Info($"ExportV2 Performance: LetterOfCreditListNoDT export to excel with range {exportOptions.Range} took {elapsedMilliseconds}ms");
            }
            var content = System.IO.File.ReadAllBytes(Path.Combine(Path.GetTempPath(), path));
            var fileName = Path.GetFileName(path);
            var downloadKey = FileHelper.PendingDownloadInstance.Add("LetterOfCreditList", content, fileName);
            _logger.Info($"ExportV2 Performance: Total export time for LetterOfCreditListNoDT: {elapsedMilliseconds}ms");
            return downloadKey;
        }



        /*<Datasource:LetterOfCreditList_LetterOfCredit:1/>*/
        /*<DataSourceFilter:LetterOfCreditList_LetterOfCredit:2/>*/
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit> Get_LetterOfCreditList_LetterOfCredit_DatasourceQueryable(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            if (shouldEvict)
            {
                @model?.Evict();
            }
            var __items = Get_LetterOfCreditList_LetterOfCredit_DatasourceQueryableImplementation(__request);
            return __items;
        }
        public IQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit> Get_LetterOfCreditList_LetterOfCredit_DatasourceQueryableImplementation(DatasourceRequest __request = null, bool shouldEvict = true)
        {
            __request = __request ?? new DatasourceRequest(0, int.MaxValue);
            var __items = new DSS5_SupplyChainFinancialsOptimisation.DAL.Repository().GetAsQueryable<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>().AsQueryable();
            var _var0 = zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentUserName();
            return __items.Where(@this => @this.Transaction.Supplier.UserName == _var0);
        }


        /*<DataSourceGetFullRecordset:LetterOfCreditList_LetterOfCredit:1/>*/

        [HttpPost]
        [Route("LetterOfCreditList_LetterOfCredit_GetFullRecordset")]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "LetterOfCredit", ClaimType = ClaimTypes.Dataset)]
        public JsonResult LetterOfCreditList_LetterOfCredit_GetFullRecordset()
        {
            var postedData = _ParsePostedData();
            var dataType = postedData["dataType"].ToString();
            var keysToExclude = postedData["keys"] == null
                                ? new List<object>()
                                : postedData["keys"].ToString()
                                .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(x => x as object)
                                .ToList();
            var indexes = postedData["indexes"] == null
                          ? null
                          : postedData["indexes"].ToString()
                          .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                          .Select(x => int.Parse(x))
                          .ToArray();
            var postedDatasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            _LoadViewModel();
            var datasourceRequest = new DatasourceRequest(0, 2147483647, postedDatasourceRequest.Filters, null, keysToExclude, indexes);
            var queryable = Get_LetterOfCreditList_LetterOfCredit_DatasourceQueryable(datasourceRequest);
            var items = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable);
            //The following method of creating DTO responses has been changed due to the fact that the returned objects were missing properties that were not used by the client.
            //It now uses the UpdateInstance method. To be removed after some testing if no problems occur.
            //var data = items.Select(i => new LetterOfCredit_LetterOfCreditDTO(i, true)).ToList();
            var data = CreateDtoInstancesFromKeys(typeof(LetterOfCreditListViewModel), dataType, items.Select(i => i.Id.ToString()).ToList(), "LetterOfCreditList_LetterOfCredit");
            var __result = Json(new
            {
                Type = "UpdateInstance",Data = Utilities.Serialize(data)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }
        /*<DataSourceEntryPoint:LetterOfCreditList_LetterOfCredit:1/>*/

        [HttpPost]
        [CustomControllerActionFilter(HasDefaultResultView=true, ActionName = "LetterOfCredit", ClaimType = ClaimTypes.Dataset)]
        [Route("LetterOfCreditList_LetterOfCredit_Datasource")]
        public JsonResult LetterOfCreditList_LetterOfCredit_Datasource()
        {
            var postedData = _LoadViewModel();
            var datasourceRequest = DeserializeDatasourceRequest(postedData["datasourceRequest"].ToString());
            var queryable = Get_LetterOfCreditList_LetterOfCredit_DatasourceQueryable(datasourceRequest);
            var response = new ListResponse
            {
                TotalRows = DatasourceRetriever.ApplyDynamicFilterToQueryable(datasourceRequest, queryable).Count(),
            };
            //Total items count
            if (CLMS.AppDev.Cache.CacheManager.Current.HasKey($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditList_LetterOfCredit_TotalItems"))
            {
                CLMS.AppDev.Cache.CacheManager.Current.Set($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditList_LetterOfCredit_TotalItems", response.TotalRows);
            }
            else
            {
                CLMS.AppDev.Cache.CacheManager.Current.Add($"{Request.RequestContext.HttpContext.Session.SessionID}_LetterOfCreditList_LetterOfCredit_TotalItems", response.TotalRows);
            }
            if (response.TotalRows < datasourceRequest.StartRow + 1)
            {
                datasourceRequest.StartRow = 0;
            }
            var _dto = DynamicDtoInfo.CreateFromPropsArray(datasourceRequest.DtoProperties);
            var _convertionMethod = _dto.GetConvertionFunc<DSS5_SupplyChainFinancialsOptimisation.BO.LetterOfCredit>();
            if (datasourceRequest.GroupBy.Any())
            {
                var groups = DatasourceRetriever.RetrieveGrouped(datasourceRequest, queryable, q => q.Id, postedData);
                var items = groups.GetAllItems();
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
                response.Groups = groups;
//Fix for total items in GetGroupsClosed
                if (datasourceRequest.GroupBy.FirstOrDefault().GetGroupsClosed)
                {
                    response.TotalRows = DatasourceRetriever.GetTotalGroups(groups);
                }
            }
            else
            {
                var items = DatasourceRetriever.Retrieve(datasourceRequest, queryable);;
                response.Data = items.ToList().Select(i => _convertionMethod(i)).ToList();
            }
            var __result = Json(new
            {
                Type = "DatasourceData",Data = Serialize(response)
            }, JsonRequestBehavior.AllowGet);
            __result.MaxJsonLength = int.MaxValue;
            return __result;
        }


        #endregion

        public override ActionResult PreActionFilterHook(bool causesValidation, bool listenToEvent, string actionName)
        {
            System.Web.HttpContext.Current.Items["_currentControllerAction"] = actionName;
            if (listenToEvent) return null;
            return null;
        }
        public override ActionResult PostActionFilterHook(bool hasDefaultResultView, bool fillDropDownInitialValues = false)
        {
            if (HasClientResponse())
            {
                viewDTO.ClientResponse = GetClientResponse();
            }
            else
            {
                var _modelDTO = new LetterOfCreditListViewModelDTO(@model);
                viewDTO.Model = _modelDTO;
            }
            if (!hasDefaultResultView)
            {
                var __result = Json(new
                {
                    Type = "Data",Data = viewDTO.Serialize()
                }, JsonRequestBehavior.AllowGet);
                __result.MaxJsonLength = int.MaxValue;
                return __result;
            }
            return View("LetterOfCreditList");
        }

        #region Data Validations


        private ActionResult GetFailedDataValidationsResult()
        {
            try
            {
                RunDataValidations();
                if (!viewDTO.DataValidationsHaveFailed) return null;
                var __result = Json(new
                {
                    Type = "RuleEvaluation",Data = viewDTO.Serialize()
                }, JsonRequestBehavior.AllowGet);
                __result.MaxJsonLength = int.MaxValue;
                return __result;
            }
            catch (Exception e)
            {
                _logger.Error("!!! DANGER: Error while evaluating Data Validations !!!", e);
                log4net.LogManager.GetLogger(this.GetType()).Error("Form: LetterOfCreditList, Action: " + System.Web.HttpContext.Current.Items["_currentControllerAction"], e);
                //throw;
                return null;
            }
        }
        public List<RuleResult> RunDataValidations()
        {
            var masterPageDataValidations = (_parentController as Controllers.MasterPageForLists.MasterPageForListsController).RunDataValidations();
            if (masterPageDataValidations?.Any() == true)
            {
                viewDTO.RuleEvaluations.DataValidations.AddRange(masterPageDataValidations);
            }
            return viewDTO.RuleEvaluations.DataValidations;
        }

        #endregion
    }
}
